### ISSUE TITLE
lp-to-jira report not functioning

### ISSUE THREAD

**Issue by kgmspark** [canonical/lp-to-jira#35]
We are using this tool to add LP bugs into our Jira project to help us manage bugs that affect our users and it's working well to import the issues. 
We would like to be able to use it to automatically update our issues, or at least pull the status for all the issues we've added, which seems like 'lp-to-jira-report' would do -0 but I am getting a 'command not found' error when I try to run that command. I can pull bugs in from LP before and after running the command so I don't think it's an API issue. 
Let me know if you have any suggestions!

**Comment by mclemenceau** [comment]
If you are using the snap the command should be lp-to-jira.report. 
Let me know if this work for you!

Thanks

**Comment by mclemenceau** [comment]
same for me actually. that line maybe at fault https://github.com/canonical/lp-to-jira/blob/5d41295581f773bc93aaf78cb4581a6f05ab0bb3/LpToJira/lp_to_jira_report.py#L345
This would be the case if your project doesn't use this Status. probably something to improve ...

**Comment by kgmspark** [comment]
I see! I just changed all the relevant ones in my jira project to 'backlog' and it works now. Thank you!
I will be working on my own branch to get it to pull the specific information we need from launchpad.
